// <auto-generated />
using System;
using DiyMusicCommunity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiyMusicCommunity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812152903_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BandImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("FormationYear")
                        .HasColumnType("int");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LogoImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MusicUrlPortal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrustStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba4dc0de-beef-cafe-f00d-b00000000001"),
                            BandContact = "convulsionsgrindcore@gmail.com",
                            Country = "Spain",
                            CreatedAt = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FormationYear = 2016,
                            GenreId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            IsClaimed = true,
                            Location = "El Ejido",
                            MusicUrlPortal = "https://convulsionsgrindcore.bandcamp.com",
                            Name = "Convulsions",
                            Status = "Active",
                            TrustStatus = "Claimed",
                            UpdatedAt = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "BandId");

                    b.ToTable("BandClaims");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Instrument")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("BandMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de4db33f-cafe-f00d-a1b2-c3d4e5f00001"),
                            BandId = new Guid("ba4dc0de-beef-cafe-f00d-b00000000001"),
                            Instrument = "Vocals",
                            IsCurrent = true,
                            Name = "Sergio Campos",
                            StartYear = 2016
                        },
                        new
                        {
                            Id = new Guid("de4db33f-cafe-f00d-a1b2-c3d4e5f00002"),
                            BandId = new Guid("ba4dc0de-beef-cafe-f00d-b00000000001"),
                            Instrument = "Guitar",
                            IsCurrent = true,
                            Name = "Hector Gonzalez",
                            StartYear = 2016
                        },
                        new
                        {
                            Id = new Guid("de4db33f-cafe-f00d-a1b2-c3d4e5f00003"),
                            BandId = new Guid("ba4dc0de-beef-cafe-f00d-b00000000001"),
                            Instrument = "Bass",
                            IsCurrent = true,
                            Name = "Binky",
                            StartYear = 2016
                        },
                        new
                        {
                            Id = new Guid("de4db33f-cafe-f00d-a1b2-c3d4e5f00004"),
                            BandId = new Guid("ba4dc0de-beef-cafe-f00d-b00000000001"),
                            Instrument = "Drums",
                            IsCurrent = true,
                            Name = "Samuel Fernandez",
                            StartYear = 2016
                        });
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandMemberOtherBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OtherBandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OtherBandId");

                    b.HasIndex("BandMemberId", "OtherBandId")
                        .IsUnique();

                    b.ToTable("BandMemberOtherBands");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("FormationYear")
                        .HasColumnType("int");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("BandProposals");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Name = "Grindcore"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Name = "Crust"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Name = "D-Beat"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-def0-234567890123"),
                            Name = "Powerviolence"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-ef01-345678901234"),
                            Name = "Punk"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-f012-456789012345"),
                            Name = "Noise"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-0123-567890123456"),
                            Name = "Goregrind"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-1234-678901234567"),
                            Name = "Gorenoise"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-5678-2345-789012345678"),
                            Name = "Death Metal"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-6789-3456-890123456789"),
                            Name = "Death-Grind"
                        });
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.ModerationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModeratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("TargetId");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LabelText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ReleaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Releases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            BandId = new Guid("ba4dc0de-beef-cafe-f00d-b00000000001"),
                            LabelText = "Hecatombe Records, Regurgitated Semen Records",
                            ReleaseDate = new DateOnly(2023, 3, 10),
                            ReleaseType = "Album",
                            Title = "Grindcore Not War",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.ReleaseFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId", "Format")
                        .IsUnique();

                    b.ToTable("ReleaseFormats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f04f0000-cafe-beef-dead-000000000001"),
                            Format = "Vinyl12",
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001")
                        },
                        new
                        {
                            Id = new Guid("f04f0000-cafe-beef-dead-000000000002"),
                            Format = "CD",
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001")
                        },
                        new
                        {
                            Id = new Guid("f04f0000-cafe-beef-dead-000000000003"),
                            Format = "Cassette",
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001")
                        });
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000001"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Crear Y Creer",
                            TrackNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000002"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Te Pudres",
                            TrackNumber = 2
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000003"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Sangre Por Dinero",
                            TrackNumber = 3
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000004"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Noche Agónica",
                            TrackNumber = 4
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000005"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "La Ley Del Padrón",
                            TrackNumber = 5
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000006"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Penitencia",
                            TrackNumber = 6
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000007"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "La Molécula",
                            TrackNumber = 7
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000008"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Crisis De Identidad",
                            TrackNumber = 8
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000009"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Todo Habrá Acabado",
                            TrackNumber = 9
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000010"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Muerte Al Mainstream",
                            TrackNumber = 10
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000011"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "La Espiral",
                            TrackNumber = 11
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000012"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "No Soy Como Tú",
                            TrackNumber = 12
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000013"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Bestia De Carne",
                            TrackNumber = 13
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000014"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "La Mosca",
                            TrackNumber = 14
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000015"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Toubkal",
                            TrackNumber = 15
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000016"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Puto Poser",
                            TrackNumber = 16
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000017"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Viejos Riders Nunca Mueren",
                            TrackNumber = 17
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000018"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Sombra Eterna",
                            TrackNumber = 18
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000019"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Nunca Ganas",
                            TrackNumber = 19
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000020"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Vacío",
                            TrackNumber = 20
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000021"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Sin Libertad",
                            TrackNumber = 21
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000022"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Fronteras",
                            TrackNumber = 22
                        },
                        new
                        {
                            Id = new Guid("c0de0000-cafe-beef-dead-000000000023"),
                            ReleaseId = new Guid("a1b2cafe-dead-beef-f00d-c0de00000001"),
                            Title = "Freya",
                            TrackNumber = 23
                        });
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiyMusicCommunity.Infrastructure.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Band", b =>
                {
                    b.HasOne("DiyMusicCommunity.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandMember", b =>
                {
                    b.HasOne("DiyMusicCommunity.Domain.Entities.Band", null)
                        .WithMany("Members")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandMemberOtherBand", b =>
                {
                    b.HasOne("DiyMusicCommunity.Domain.Entities.BandMember", null)
                        .WithMany("OtherBands")
                        .HasForeignKey("BandMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyMusicCommunity.Domain.Entities.Band", "OtherBand")
                        .WithMany()
                        .HasForeignKey("OtherBandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtherBand");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Release", b =>
                {
                    b.HasOne("DiyMusicCommunity.Domain.Entities.Band", "Band")
                        .WithMany("Releases")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.ReleaseFormat", b =>
                {
                    b.HasOne("DiyMusicCommunity.Domain.Entities.Release", null)
                        .WithMany("Formats")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Track", b =>
                {
                    b.HasOne("DiyMusicCommunity.Domain.Entities.Release", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DiyMusicCommunity.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DiyMusicCommunity.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyMusicCommunity.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DiyMusicCommunity.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Band", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.BandMember", b =>
                {
                    b.Navigation("OtherBands");
                });

            modelBuilder.Entity("DiyMusicCommunity.Domain.Entities.Release", b =>
                {
                    b.Navigation("Formats");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
